"""cases table

Revision ID: adb5910f2add
Revises: 
Create Date: 2020-09-16 18:33:38.500386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb5910f2add'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('onCampusStudents', sa.Integer(), nullable=True),
    sa.Column('offCampusStudents', sa.Integer(), nullable=True),
    sa.Column('nonCampusStudents', sa.Integer(), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_case_date'), 'daily_case', ['date'], unique=True)
    op.create_index(op.f('ix_daily_case_employees'), 'daily_case', ['employees'], unique=False)
    op.create_index(op.f('ix_daily_case_nonCampusStudents'), 'daily_case', ['nonCampusStudents'], unique=False)
    op.create_index(op.f('ix_daily_case_offCampusStudents'), 'daily_case', ['offCampusStudents'], unique=False)
    op.create_index(op.f('ix_daily_case_onCampusStudents'), 'daily_case', ['onCampusStudents'], unique=False)
    op.create_index(op.f('ix_daily_case_total'), 'daily_case', ['total'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_case_total'), table_name='daily_case')
    op.drop_index(op.f('ix_daily_case_onCampusStudents'), table_name='daily_case')
    op.drop_index(op.f('ix_daily_case_offCampusStudents'), table_name='daily_case')
    op.drop_index(op.f('ix_daily_case_nonCampusStudents'), table_name='daily_case')
    op.drop_index(op.f('ix_daily_case_employees'), table_name='daily_case')
    op.drop_index(op.f('ix_daily_case_date'), table_name='daily_case')
    op.drop_table('daily_case')
    # ### end Alembic commands ###
