"""tests table

Revision ID: b13b3eeac305
Revises: adb5910f2add
Create Date: 2020-09-16 20:33:19.960254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13b3eeac305'
down_revision = 'adb5910f2add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=64), nullable=True),
    sa.Column('total_tested', sa.Integer(), nullable=True),
    sa.Column('positive_cases', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_test_positive_cases'), 'weekly_test', ['positive_cases'], unique=False)
    op.create_index(op.f('ix_weekly_test_timeframe'), 'weekly_test', ['timeframe'], unique=True)
    op.create_index(op.f('ix_weekly_test_total_tested'), 'weekly_test', ['total_tested'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_test_total_tested'), table_name='weekly_test')
    op.drop_index(op.f('ix_weekly_test_timeframe'), table_name='weekly_test')
    op.drop_index(op.f('ix_weekly_test_positive_cases'), table_name='weekly_test')
    op.drop_table('weekly_test')
    # ### end Alembic commands ###
